//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeACatClient.MakeACatServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CatBreed", Namespace="http://schemas.datacontract.org/2004/07/MakeACatWCFServiceApplication")]
    public enum CatBreed : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Abyssinian = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        American_Shorthair = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bengal = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        British_Longhair = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Maine_Coon = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenderType", Namespace="http://schemas.datacontract.org/2004/07/MakeACatWCFServiceApplication")]
    public enum GenderType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Male = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Female = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cat", Namespace="http://schemas.datacontract.org/2004/07/MakeACatWCFServiceApplication")]
    [System.SerializableAttribute()]
    public partial class Cat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MakeACatClient.MakeACatServiceRef.CatBreed BreedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MakeACatClient.MakeACatServiceRef.GenderType GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Drawing.Bitmap PhotoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MakeACatClient.MakeACatServiceRef.CatBreed Breed {
            get {
                return this.BreedField;
            }
            set {
                if ((this.BreedField.Equals(value) != true)) {
                    this.BreedField = value;
                    this.RaisePropertyChanged("Breed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MakeACatClient.MakeACatServiceRef.GenderType Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Drawing.Bitmap Photo {
            get {
                return this.PhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoField, value) != true)) {
                    this.PhotoField = value;
                    this.RaisePropertyChanged("Photo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="CatList", Namespace="http://schemas.datacontract.org/2004/07/MakeACatWCFServiceApplication", ItemName="Cat")]
    [System.SerializableAttribute()]
    public class CatList : System.Collections.Generic.List<MakeACatClient.MakeACatServiceRef.Cat> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MakeACatServiceRef.IMakeACatService")]
    public interface IMakeACatService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakeACatService/MakeACat", ReplyAction="http://tempuri.org/IMakeACatService/MakeACatResponse")]
        MakeACatClient.MakeACatServiceRef.Cat MakeACat(string name, MakeACatClient.MakeACatServiceRef.CatBreed breed, MakeACatClient.MakeACatServiceRef.GenderType gender, int age);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakeACatService/MakeACat", ReplyAction="http://tempuri.org/IMakeACatService/MakeACatResponse")]
        System.Threading.Tasks.Task<MakeACatClient.MakeACatServiceRef.Cat> MakeACatAsync(string name, MakeACatClient.MakeACatServiceRef.CatBreed breed, MakeACatClient.MakeACatServiceRef.GenderType gender, int age);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakeACatService/MakeCats", ReplyAction="http://tempuri.org/IMakeACatService/MakeCatsResponse")]
        MakeACatClient.MakeACatServiceRef.CatList MakeCats();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakeACatService/MakeCats", ReplyAction="http://tempuri.org/IMakeACatService/MakeCatsResponse")]
        System.Threading.Tasks.Task<MakeACatClient.MakeACatServiceRef.CatList> MakeCatsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMakeACatServiceChannel : MakeACatClient.MakeACatServiceRef.IMakeACatService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MakeACatServiceClient : System.ServiceModel.ClientBase<MakeACatClient.MakeACatServiceRef.IMakeACatService>, MakeACatClient.MakeACatServiceRef.IMakeACatService {
        
        public MakeACatServiceClient() {
        }
        
        public MakeACatServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MakeACatServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MakeACatServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MakeACatServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MakeACatClient.MakeACatServiceRef.Cat MakeACat(string name, MakeACatClient.MakeACatServiceRef.CatBreed breed, MakeACatClient.MakeACatServiceRef.GenderType gender, int age) {
            return base.Channel.MakeACat(name, breed, gender, age);
        }
        
        public System.Threading.Tasks.Task<MakeACatClient.MakeACatServiceRef.Cat> MakeACatAsync(string name, MakeACatClient.MakeACatServiceRef.CatBreed breed, MakeACatClient.MakeACatServiceRef.GenderType gender, int age) {
            return base.Channel.MakeACatAsync(name, breed, gender, age);
        }
        
        public MakeACatClient.MakeACatServiceRef.CatList MakeCats() {
            return base.Channel.MakeCats();
        }
        
        public System.Threading.Tasks.Task<MakeACatClient.MakeACatServiceRef.CatList> MakeCatsAsync() {
            return base.Channel.MakeCatsAsync();
        }
    }
}
